# ADD DOCKER COMPOSE CONFIGURATION
version: "3.9"  # optional since v1.27.0
services:
  jupyter:
    build: .
    # image: angelash/datascience-notebook
    image:  jupyter/pyspark-notebook
    ports:
      - "9090:8888"
    volumes:
      - .:/home/jovyan/work